### ISSUE TITLE
Issue of rekey and packet number processing

### ISSUE THREAD

**Issue by byu343** [sonic-net/sonic-wpa-supplicant#38]
We found an issue in our testing scenario without rekey_period. Under such a setting, when the packet number for egress is increased to over a certain threshold, the key has to switchover to a new one, to avoid the packet number overflow. But it seems the switchover, i.e., macsec_sonic_create_transmit_sa() is not initiated by the wpa-supplicant. This is probably because the callback functions related to packet numbers in src/drivers/driver_macsec_sonic.c currently do not interact with the macsec chip but only read/write counter database.  To bypass the issue, our workaround is to set an explicit rekey_period.

**Comment by rlhui** [comment]
@Pterosaur - would you please check this issue?  Thanks.

**Comment by Pterosaur** [comment]
I will check it and reply ASAP.

**Comment by Pterosaur** [comment]
I only found the refresh SAK issue in Linux MACsec driver instead of SONiC MACsec driver. So, I fix the rekey issue in Linux MACsec driver by the PR: https://github.com/Azure/sonic-wpa-supplicant/pull/42. After that, I did the following experiment to verify the issue.
              My experiment is by re-compiling the wpa_supplicant to decrease the PENDDING_PN_EXAHUSTING at https://github.com/Azure/sonic-wpa-supplicant/blob/457e94d516582b046f9d7e794e58c82145ec350c/src/pae/ieee802_1x_kay.c#L34-L35 which will trigger the rekey action if the PN number comes to over 256.
![image](https://user-images.githubusercontent.com/18609639/142311880-3e0ac3d5-f1f8-4a5f-8839-817271117945.png)
              And then, I connect a SONiC VM with SONiC MACsec driver to a server with Linux MACsec driver. You can see the following output.
![image](https://user-images.githubusercontent.com/18609639/142312047-4c3ced2b-f0f9-440d-b3fe-ec8908950f3c.png)

  The rekey action looks good. Can this experiment confirm the issue you mentioned?

**Comment by Pterosaur** [comment]
Cannot reproduce
